name: Lint

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*"
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  super-linter:
    uses: harryzcy/github-actions/.github/workflows/linter.yml@702521529f0ebea89257b1297490379a0ec56976 # main

  spelling:
    uses: harryzcy/github-actions/.github/workflows/spelling.yml@702521529f0ebea89257b1297490379a0ec56976 # main
